version: '3'
services:
  db-service:
    image: mysql:8.0
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: gc
      MYSQL_PASSWORD: Gc@12345
      MYSQL_DATABASE: bc_25_gc
    volumes:
      - db-data:/var/lib/mysql
    networks:
     - compose-network


  backend:
     image: bc-backend
     ports:
     - "8000:8000"
     environment:
      MYSQL_HOST: db-service
      MYSQL_USER: gc
      MYSQL_PASSWORD: Gc@12345
     depends_on:
       - db-service
     networks:
      - compose-network

  frontend:
     image: bc-frontend
     ports:
       - "8004:80"
     depends_on:
        - backend
        - db-service
     networks:
      - compose-network



volumes:
  db-data:
networks:
  compose-network:
   driver: bridge

   