version: '3'
services:
  backend:
     image: bc-backend
     ports:
     - "8000:8000"
     environment:
      MYSQL_HOST: db-service
      MYSQL_USER: gc
      MYSQL_PASSWORD: Gc@12345
     depends_on:
       - db-service
     networks:
      - compose-network

  frontend:
     image: bc-frontend
     ports:
       - "8004:80"
     depends_on:
        - backend
        - db-service
     networks:
      - compose-network



volumes:
  db-data:
networks:
  compose-network:
   driver: bridge

   