version: '3'
services:
  db-service:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: gc
      MYSQL_PASSWORD: Gc@12345
      MYSQL_DATABASE: bc_25_gc
    volumes:
       db-data:/var/lib/mysql
    networks:
      - bc_25_gc_network

  backend:
     image: bc-backend
     ports:
     - "8000:8080"
     environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db-service:3306/bc_25_gc
        SPRING_DATASOURCE_USERNAME: gc
        SPRING_DATASOURCE_PASSWORD: Gc@12345
     networks:
      - bc_25_gc_network

  frontend:
     image: bc-frontend
     ports:
       - "80:80"
     depends_on:
        - be-service
        - db-service
     networks:
      - bc_25_gc_network


volumes:
  db-data:
networks:
  bc_25_gc_network
   